### PR TITLE
(1.21.1) Fix crash when placing vertical slab into water

### LINKED ISSUE #311: Vertical slabs crash the game when placed in water (and prevent reloading world)
Issue:

As the title says, when you place a vertical slab into a block of water the game crashes and then prevents the world from reloading. However, if a vertical slab is water-logged by right-clicking on it with a water bucket, or by 2 adjacent water source blocks flowing into it, no crash occurs. Additionally, if you water-log a vertical slab in one of those ways, you can then place any other vertical slab in the same water-logged block to make a double vertical slab without a crash. The crash only occurs when you directly place a vertical slab into water.

To Replicate:

1. Install DoubleSlabs mod
2. Obtain a vertical slab block
3. Place the vertical slab into a block of water by right-clicking

Result:

Crash - Log: [https://mclo.gs/HbNigyf](https://mclo.gs/HbNigyf)

Expected Result:

Water-logged vertical slab should be placed

Versions Tested:

- DoubleSlabs-Forge-1.20.1-0.1.2 (on Forge v. 1.20.1-47.4.5)
- DoubleSlabs-Fabric-1.20.1-0.1.0 (w/ Fabric API v. 1.20.1-0.92.6 - on Fabric v. 1.20.1-0.17.2)
- DoubleSlabs-NeoForge-1.21.1-0.2.3 (on NeoForge v. 21.1.200)

(The bug appears to affect all versions but I am mostly interested in a fix for the Forge 1.20.1 version because that is the one I was playing haha)

### PR DESCRIPTION
**Pull request by throckmorpheus**
Fixes  #311 - **Vertical slabs crash the game when placed in water (and prevent reloading world)**

It was trying to use the block state to index into a map of maps, but wasn't unsetting `waterlogged` on the indexing block state first, so it ended up dereferencing a null pointer.
From what I can see this fixes both the initial crash and the inability to load back into the world afterwards on all three loaders.

Presumably the same fix will have to be added for the other game versions too.

### CODE REVIEW

File: common/src/main/java/cjminecraft/doubleslabs/library/helpers/VerticalSlabModelHelper.java [hunk 1]
```diff
@@ -20,7 +21,8 @@ public VerticalSlabModelHelper(Map<BlockState, Map<Direction, BakedModel>> verti
 
     @Override
     public BakedModel getVerticalSlabModel(BlockState state, Direction side) {
-        return verticalModels.get(state).get(side);
+		final var normalisedState = state.setValue(BlockStateProperties.WATERLOGGED, false);
```
Comment (CJMinecraft01) [inline common/src/main/java/cjminecraft/doubleslabs/library/helpers/VerticalSlabModelHelper.java:24]: I think it's safer to use `trySetValue` here in case the state doesn't have the `WATERLOGGED` property.
```suggestion
		final var normalisedState = state.trySetValue(BlockStateProperties.WATERLOGGED, false);
```

**Review by CJMinecraft01 — CHANGES_REQUESTED** [review]
Thanks for spotting this simple fix! 🚀  Just a small comment on using `trySetValue` over `setValue`.
